var aircoms={
"9U":"Air Moldova",
"7W":"Windrose Airlines",
A3:"Aegean Airlines",
A9:"Georgian Airways",
AA:"American Airlines",
AB:"Air Berlin",
AC:"Air Canada",
AE:"Mandarin Airlines",
AF:"Air France",
AG:"Air Contractors (UK) Limited",
AH:"Air Algerie",
AI:"Air India",
AM:"Aeromexico",
AP:"Air One S.p.A.",
AR:"Aerolineas Argentinas",
AS:"Alaska Airlines",
AT:"Royal Air Maroc",
AU:"Austral Lineas Aereas",
AV:"Avianca",
AY:"Finnair",
AZ:"Alitalia S.p.A.",
B1:"Air Bucharest",
B2:"Белавиа",
B3:"Bellview Airlines",
B7:"Uni Air",
BA:"British Airways",
BD:"bmi",
BE:"flybe.British European",
BG:"Biman",
BI:"Royal Brunei",
BJ:"Nouvelair",
BL:"Jetstar Pacific Airlines",
BO:"BB Airways",
BP:"Air Botswana",
BR:"Eva Air",
BT:"Air Baltic",
BU:"SAS Norge",
BV:"Blue Panorama",
BW:"Caribbean Airlines",
C4:"Alma de Mexico",
C9:"Cirrus Airlines",
C9:"Skywise",
CA:"Air China Limited",
CG:"PNG Air",
CI:"China Airlines",
CK:"China Cargo Airlines Ltd.",
CL:"Lufthansa CityLine",
CM:"Copa Airlines",
CO:"Continental Airlines",
CS:"Continental Micronesia",
CU:"Cubana",
CV:"Air Chathams",
CV:"Cargolux S.A.",
CX:"Cathay Pacific",
CY:"Cyprus Airways",
CZ:"China Southern Airlines",
D0:"DHL Air Ltd",
D6:"Interair",
D9:"Donavia (Донавиа)",
DD:"Nok Air",
DL:"Delta Air Lines",
DN:"Senegal Airlines",
DP:"Pobeda (Победа)",
DT:"TAAG Angola Airlines",
DU:"Hemus Air",
DY:"Norwegian Air Shuttle",
E3:"NewGen Airways",
E8:"City Airways",
ED:"AirExplore",
EI:"Aer Lingus",
EK:"Emirates Airline",
EP:"Iran Aseman Airlines",
ES:"DHL International E.C.",
ET:"Ethiopian Airlines",
EL:"Ellinair",
EW:"Eurowings",
EY:"Etihad Airways",
FA:"FlySafair",
FB:"Bulgaria Air",
FE:"Far Eastern Air Transport",
FG:"Ariana Afghan Airlines",
FH:"Freebird Airlines",
FI:"Icelandair",
FJ:"Air Pacific",
FM:"Shanghai Airlines",
FN:"Fastjet Zimbabwe",
FO:"Felix Airways",
FV:"Rossiya - Russian Airlines (Россия)",
FX:"Federal Express",
FZ:"Flydubai",
G2:"Albatros Airlines",
G9:"Air Arabia",
GA:"Garuda",
GE:"TransAsia Airways",
GF:"Gulf Air",
GG:"Goma Air",
H1:"Ernest Airlines",
H9:"Pegasus Airlines",
HF:"Hapag Lloyd",
HG:"Niki",
HJ:"Hellas Jet",
HM:"Air Seychelles",
HN:"Afghan Jet International",
HP:"Amapola Flyg",
HR:"Hahn Air",
HU:"Hainan Airlines",
HY:"Uzbekistan Airways",
HZ:"Aurora (Аврора)",
I4:"I fly",
IB:"Iberia",
IE:"Solomon Airlines",
IG:"Meridiana",
IN:"MAT - Macedonian Airlines",
IR:"Iran Air",
IT:"Tigerair Taiwan",
IY:"Yemenia",
IZ:"Arkia Israeli Airlines Ltd",
J2:"Azerbaijan Airlines",
JA:"B & H Airlines",
JE:"Mango",
JF:"Jet Asia Airways",
JJ:"TAM Linhas Aereas",
JK:"Spanair",
JL:"Japan Airlines",
JM:"Air Jamaica Limited",
JO:"JALways Co. Ltd",
JP:"Adria Airways",
JS:"Air Koryo",
JU:"Jat Airways",
JY:"InterCaribbean Airways",
JZ:"Skyways",
K8:"Kan Air",
KA:"Dragonair",
KC:"Air Astana",
KE:"Korean Air",
KF:"Blue1",
KK:"Atlasglobal",
KL:"KLM",
KM:"Air Malta p.l.c.",
KP:"ASKY Airlines",
KQ:"Kenya Airways",
KU:"Kuwait Airways",
KZ:"Nippon Cargo Airlines (NCA)",
LA:"Lan Airline",
LC:"Varig Log",
LG:"Luxair",
LH:"Lufthansa",
LI:"LIAT",
LN:"Libyan Airlines",
LO:"LOT Polish Airlines",
LP:"Lan Peru",
LR:"Lacsa",
LT:"LTU",
LX:"Swiss",
LY:"EL AL",
M9:"Мотор Сич",
MA:"Malev",
MD:"Air Madagascar",
ME:"MEA",
MF:"Xiamen Airlines",
MH:"Malaysia Airlines",
MI:"Silkair",
MK:"Air Mauritius",
MN:"Comair",
MN:"Kulula.com",
MS:"Egyptair",
MU:"China Eastern",
MX:"Mexicana",
N4:"Nordwind Airlines",
N9:"Novair",
NF:"Air Vanuatu",
NG:"Lauda Air",
NH:"All Nippon Airways",
NI:"PGA-Portugalia Airlines",
NI:"Portugalia Airlines",
NL:"Shaheen Air International",
NN:"VIM Airlines (ВИМ-Авиа)",
NT:"Binter Canarias",
NW:"Northwest Airlines",
NX:"Air Macau",
NZ:"Air New Zealand",
OA:"Olympic Airlines S.A.",
OK:"Czech Airlines",
OL:"Polynesian Airlines",
OM:"MIAT",
OS:"Austrian Airlines",
OU:"Croatia Airlines",
OV:"Estonian Air",
OX:"Orient Thai Airlines",
OY:"Andes Lineas Aereas",
OZ:"Asiana",
PA:"Airblue",
PC:"Pegasus Airlines",
PE:"People's Viennaline",
PG:"Bangkok Airways",
PK:"Pakistan International Airlines",
PR:"Philippine Airlines",
PS:"МАУ",
PU:"Pluna",
PW:"Precision Air",
PX:"Air Niugini",
PY:"Surinam Airways",
PZ:"TAM - Transportes Aereos del Mercosur",
Q3:"Anguilla Air Services",
QE:"Qatar Executive",
QF:"Qantas",
QI:"Cimber Air",
QL:"Laser Airlines",
QM:"Air Malawi",
QN:"Air Armenia",
QR:"Qatar Airways",
QS:"SmartWings",
QW:"Blue Wings",
QY:"European Air Transport",
R2:"Orenair (Оренбургские авиалинии)",
R3:"Yakutia Airlines (Якутия)",
R5:"Jordan Aviation",
R7:"Aserca Airlines",
RA:"Nepal Airlines",
RB:"Syrianair",
RJ:"Royal Jordanian",
RK:"R Airlines",
RM:"Armenia Aircompany",
RO:"TAROM",
RQ:"Kam Air",
RV:"Caspian Airlines",
S2:"Jet Lite (India) Limited",
S3:"SBA Airlines",
S4:"SATA Internacional",
S7:"S7 Airlines (Сибирь)",
SA:"South African Airways",
SB:"Aircalin",
SC:"Shandong Airlines Co Ltd",
SD:"Sudan Airways",
SF:"Tassili Airlines",
SH:"Simrik Airlines",
SK:"SAS",
SL:"Thai Lion Air",
SN:"Brussels Airlines",
SP:"SATA Air Acores",
SQ:"Singapore Airlines",
SQ:"Singapore Airlines Cargo",
SS:"Corsair",
SU:"Aeroflot (Аэрофлот)",
SV:"Saudi Arabian Airlines",
SW:"Air Namibia",
T0:"Avianca Peru",
TA:"Avianca El Salvador",
TA:"TACA",
TC:"Air Tanzania",
TE:"FlyLAL - Lithuanian Airlines",
TF:"Braathens Regional Airlines",
TF:"Malmo Aviation",
TG:"Thai Airways",
TI:"Tailwind Airlines",
TK:"AnadoluJet",
TK:"Turkish Airlines",
TM:"LAM",
TN:"Air Tahiti Nui",
TP:"TAP Portugal",
TR:"Tigerair",
TS:"Air Transat",
TU:"Tunisair",
TZ:"Scoot",
U4:"Buddha Air",
U6:"Ural Airlines (Уральские авиалинии)",
UA:"United Airlines",
UC:"Lan Chile Cargo",
UG:"Tunisair Express",
UH:"AtlasGlobal Украина",
UL:"SriLankan",
UM:"Air Zimbabwe",
UN:"Transaero (Трансаэро)",
UO:"Hong Kong Express Airways Limited",
US:"US Airways, Inc.",
UT:"UTair (ЮТэйр)",
UU:"Air Austral",
UX:"Air Europa",
V0:"Conviasa",
V3:"Carpatair",
V6:"VI Airlink",
V7:"Air Senegal International",
VH:"Aeropostal Alas de Venezuela",
VI:"Volga-Dnepr Airlines (Волга-Днепр)",
VJ:"VietJet Air",
VK:"Virgin Nigeria",
VL:"Air VIA",
VN:"Venezolana",
VN:"Vietnam Airlines",
VO:"Tyrolean Airways",
VS:"Virgin Atlantic",
VT:"Air Tahiti",
VU:"Veca Airlines",
VV:"Aerosvit Airlines",
W2:"Flexflight",
W5:"Mahan Air",
W8:"Cargojet Airways Ltd.",
WB:"Rwandair",
WE:"Thai Smile",
WF:"Wideroe",
WM:"Winair",
WX:"CityJet",
WY:"Oman Air",
WZ:"Red Wings Airlines",
X5:"Ten Airways",
XC:"Corendon Airlines",
XF:"Vladivostok Air (Владивосток Авиа)",
XK:"CCM Airlines",
XL:"LanEcuador",
XQ:"SunExpress",
XV:"BVI Airways",
XW:"NokScoot",
XY:"Flynas",
XZ:"South African Express",
Y7:"NordStar",
Y9:"Kish Air",
YB:"Borajet",
YC:"Yamal Airlines (Ямал)",
YE:"Yanair",
YM:"Montenegro Airlines",
YT:"Tara Air",
YT:"Yeti Airlines",
YU:"EuroAtlantic Airways",
VY:"Vueling Airlines",
YW:"Air Nostrum",
YZ:"Alas Uruguay",
Z6:"Днеправиа",
ZD:"Ewa Air",
ZF:"Azur Air",
ZH:"Shenzhen Airlines Co Ltd",
ZI:"Aigle Azur",
ZV:"V Air"
}
